name		'juniorsysadmin-ubuntuzilla'
version		'0.0.2' 
source		'git://github.com/juniorsysadmin/puppet-ubuntuzilla.git'
author		'Ben Spiccia'
summary		'Module for installing the Ubuntuzilla repository'
description 	'This module installs the Ubuntuzilla repository which hosts up to date versions of Mozilla Firefox, Thunderbird and Seamonkey.'
license     	'Apache License, Version 2.0'

dependency  'puppetlabs/apt', '>= 1.0.0'
project_page 'https://github.com/juniorsysadmin/puppet-ubuntuzilla'
issues_url 'https://github.com/juniorsysadmin/puppet-ubuntuzilla/issues'
